name: Deploy to AWS Docker on merge

on:
  push:
    branches:
      - prod

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./moo_kra_ta_news
          file: ./moo_kra_ta_news/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/se331-frontend:latest

      - name: Ensure target folder exists on server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST_SERVER }}
          username: ${{ secrets.HOST_USER_NAME }}
          key: ${{ secrets.HOST_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            mkdir -p /home/ubuntu/frontend
            rm -rf /home/ubuntu/frontend/docker-compose.yml

      - name: Copy docker-compose.yml via SSH
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.HOST_SERVER }}
          username: ${{ secrets.HOST_USER_NAME }}
          key: ${{ secrets.HOST_SSH_PRIVATE_KEY }}
          port: 22
          source: "moo_kra_ta_news/docker-compose.yml"
          target: "/home/ubuntu/frontend/"

      - name: Docker compose deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST_SERVER }}
          username: ${{ secrets.HOST_USER_NAME }}
          key: ${{ secrets.HOST_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/frontend/moo_kra_ta_news
            echo "Listing files:"
            ls -R /home/ubuntu/frontend
            echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
            docker compose -f docker-compose.yml down || true
            docker compose -f docker-compose.yml pull
            docker compose -f docker-compose.yml up -d

